spring:
  application:
    name: ms-customer
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://devuser:devpassword@localhost:27017/customer_db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
